components:
  schemas:
    Balance:
      description: Response model for user balance.
      properties:
        balance:
          title: Balance
          type: number
        currency:
          default: rub
          maxLength: 3
          minLength: 3
          title: Currency
          type: string
        status_code:
          default: 200
          exclusiveMaximum: 600.0
          minimum: 100.0
          title: Status Code
          type: integer
        user_id:
          exclusiveMinimum: 0.0
          title: User Id
          type: integer
      required:
      - user_id
      - balance
      title: Balance
      type: object
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    Operation:
      description: Request model for change user balance.
      properties:
        description:
          title: Description
          type: string
        operation:
          $ref: '#/components/schemas/OperationType'
        total:
          exclusiveMinimum: 0.0
          title: Total
          type: number
        user_id:
          exclusiveMinimum: 0.0
          title: User Id
          type: integer
      required:
      - operation
      - user_id
      - total
      title: Operation
      type: object
    OperationType:
      description: Operations types for transactions.
      enum:
      - replenishment
      - withdraw
      title: OperationType
      type: string
    PageOut:
      description: Response model for user account transactions history request.
      properties:
        content:
          items:
            type: object
          title: Content
          type: array
      required:
      - content
      title: PageOut
      type: object
    SortKey:
      description: Sort order for sort keys.
      enum:
      - desc
      - asc
      title: SortKey
      type: string
    Transaction:
      description: Request model for transfer funds between user accounts.
      properties:
        description:
          title: Description
          type: string
        recipient_id:
          exclusiveMinimum: 0.0
          title: Recipient Id
          type: integer
        sender_id:
          exclusiveMinimum: 0.0
          title: Sender Id
          type: integer
        total:
          exclusiveMinimum: 0.0
          title: Total
          type: number
      required:
      - sender_id
      - recipient_id
      - total
      title: Transaction
      type: object
    ValidationError:
      properties:
        loc:
          items:
            type: string
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
info:
  title: FastAPI
  version: 0.1.0
openapi: 3.0.2
paths:
  /account/create/user_id/{user_id}:
    post:
      description: Create user account.
      operationId: create_user_acc_account_create_user_id__user_id__post
      parameters:
      - in: path
        name: user_id
        required: true
        schema:
          exclusiveMinimum: 0.0
          title: User Id
          type: integer
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Create User Acc
  /account/delete/user_id/{user_id}:
    delete:
      description: Delete user account.
      operationId: delete_user_acc_account_delete_user_id__user_id__delete
      parameters:
      - in: path
        name: user_id
        required: true
        schema:
          exclusiveMinimum: 0.0
          title: User Id
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Delete User Acc
  /balance/change:
    post:
      description: Change user balance.
      operationId: change_user_balance_balance_change_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Operation'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Change User Balance
  /balance/get/user_id/{user_id}:
    get:
      description: Get user account balance.
      operationId: get_user_balance_balance_get_user_id__user_id__get
      parameters:
      - description: external user id
        in: path
        name: user_id
        required: true
        schema:
          description: external user id
          title: User Id
          type: integer
      - description: currency alias for balance value presentation
        in: query
        name: currency
        required: false
        schema:
          default: rub
          description: currency alias for balance value presentation
          maxLength: 3
          minLength: 3
          title: Currency
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Balance'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Get User Balance
  /transactions/history/user_id/{user_id}:
    get:
      description: Get history of user account transactions.
      operationId: get_user_history_transactions_history_user_id__user_id__get
      parameters:
      - description: external user id
        in: path
        name: user_id
        required: true
        schema:
          description: external user id
          exclusiveMinimum: 0.0
          title: User Id
          type: integer
      - description: number of records per page
        in: query
        name: page_size
        required: false
        schema:
          default: 20
          description: number of records per page
          exclusiveMinimum: 0.0
          maximum: 100.0
          title: Page Size
          type: integer
      - description: nuber of neccessary page
        in: query
        name: page_number
        required: false
        schema:
          default: 1
          description: nuber of neccessary page
          exclusiveMinimum: 0.0
          title: Page Number
          type: integer
      - description: sort order by transaction date
        in: query
        name: order_by_date
        required: false
        schema:
          allOf:
          - $ref: '#/components/schemas/SortKey'
          description: sort order by transaction date
      - description: sort order by transaction total value
        in: query
        name: order_by_total
        required: false
        schema:
          allOf:
          - $ref: '#/components/schemas/SortKey'
          description: sort order by transaction total value
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageOut'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Get User History
  /transactions/transfer:
    post:
      description: Transfer funds from one account to another.
      operationId: transfer_between_users_transactions_transfer_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Transfer Between Users
